FROM node:16-alpine3.14

WORKDIR /usr/src/app

RUN yarn global add serve
COPY ["package.json", "yarn.lock", "./"]
RUN yarn install

EXPOSE 8000

ARG ENV_FILE
RUN echo "$ENV_FILE" > .env

ENV PORT=8000
ENV NODE_ENV=production

COPY . .

RUN yarn build
CMD [ "serve", "-s", "build"]
